@api = http://localhost:5000

POST {{api}}/product/createProducts
Content-Type: application/json

[
        {
            "id_producto": 3304,
            "nombre": "Shampoo Repelente Natural Protección Y Cuidado - 300 Ml",
            "categoria": "Limpieza",
            "marca": "Maskota",
            "precio": 23.60,
            "imagen": ""
        },
        {
            "id_producto": 3303,
            "nombre": "Shampoo Belleza Control De Olores - 300 Ml",
            "categoria": "Limpieza",
            "marca": "Maskota",
            "precio": 23.60,
            "imagen":"" 
        },
        {
        "id_producto": 2409,
        "nombre": "Aro De Goma Strong - ø15 Cm",
        "categoria": "Accesorios",
        "marca": "CanCat",
        "precio": "87.40",
        "imagen":""
        },
        {
        "id_producto": 1601,
        "nombre": "Cat Chow Adulto Pescado - 3 Kg",
        "categoria": "Alimentos",
        "marca": "Cat Chow",
        "precio": 40,
        "imagen":""
        }      
]




{
    "id_producto": 3304,
    "nombre": "Shampoo Repelente Natural Protección Y Cuidado - 300 Ml",
    "categoria": "Limpieza",
    "marca": "Maskota",
    "precio": 23.60,
    "imagen": "" 
}

{
    "id_producto": 3302,
    "nombre": "Shampoo En Gel Canela Y Manzana Maskota - 300 Ml",
    "categoria": "Limpieza",
    "marca": "Maskota",
    "precio": "23.60",
    "imagen":""
}

{
    "id_producto": 3301,
    "nombre": "Shampoo Maskota Pelaje Blanco Revitaluzante De Color - 300 Ml",
    "categoria": "Limpieza",
    "marca": "Maskota",
    "precio": 23.60,
    "imagen":""
}
{
    "id_producto": 3202,
    "nombre": "Dentastix Pedigree Razas Pequeñas",
    "categoria": "Limpieza",
    "marca": "Pedigree",
    "precio": 6,
    "imagen":""
}
{
    "id_producto": 3201,
    "nombre": "Dentastix Pedigree Razas Medianas",
    "categoria": "Limpieza",
    "marca": "Pedigree",
    "precio": 8,
    "imagen":""
}
{
    "id_producto": 3107,
    "nombre": "Mordillo Gumi Dental Con Cordon - Chico",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 70,
    "imagen":"" 
}
{
    "id_producto": 3106,
    "nombre": "Mordillo Dogit Gumi Con Seda Dental - Mediano",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 58,
    "imagen":""
}
{
    "id_producto": 3105,
    "nombre": "Mordillo Gumi Dental En Forma De Hueso - Mini",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 25,
    "imagen":"" 
}
{
    "id_producto": 3104,
    "nombre": "Paños Sanitarios Dogit 14 Unidades - 55,8x55,8 Cm",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 40,
    "imagen":""
}
{
    "id_producto": 3103,
    "nombre": "Paños Sanitarios Dogit 30 Unidades - 55,8x55,8 Cm",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 84,
    "imagen":""
}
{
    "id_producto": 3102,
    "nombre": "Paños Sanitarios Dogit 50 Unidades - 55,8x55,8 Cm",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 104,
    "imagen":""
}
{
    "id_producto": 3101,
    "nombre": "Corta Uñas Dogit Profesional",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 70,
    "imagen":""
}
{
    "id_producto": 2410,
    "nombre": "Transportadora Cancat Skudo 3 - 60x40x39",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 422.40,
    "imagen":"" 
}
{
    "id_producto": 2409,
    "nombre": "Aro De Goma Strong - ø15 Cm",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": "87.40",
    "imagen":""
}
{
    "id_producto": 2408,
    "nombre": "Pelota Rayada Cancat - 7 Cm",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 15.90,
    "imagen":""
}
{
    "id_producto": 2407,
    "nombre": "Hueso Dental Cancat",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 20.30,
    "imagen":""
}
{
    "id_producto": 2406,
    "nombre": "Litera Cerrada Cancat Komoda Con Palita Y Filtro De Carbono - Litera Cancat Komoda Con Palita Y Filtro De Carbono",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 191.10,
    "imagen":"" 
}
{
    "id_producto": 2405,
    "nombre": "Peluche Raton Duo Cancat Smart Antiestres",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 43.50,
    "imagen":""
}
{
    "id_producto": 2404,
    "nombre": "Juguete Cancat Raton con Sonido",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 30.00,
    "imagen":""
}
{
    "id_producto": 2403,
    "nombre": "Mordillo Cancat Dental",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 36.60,
    "imagen":""
}
{
    "id_producto": 2402,
    "nombre": "Cañita Pez Esqueleto Blanco - Tamaño Único",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 42.30,
    "imagen":""
}
{
    "id_producto": 2401,
    "nombre": "Juguete CanCat Soga Con Doble Nudo - 13 pulgadas",
    "categoria": "Accesorios",
    "marca": "CanCat",
    "precio": 19.50,
    "imagen":""
}
{
    "id_producto": 1705,
    "nombre": "Alimento Dog Chow Sano y En Forma para Perro Adulto - 8kg",
    "categoria": "Alimentos",
    "marca": "Dog Chow",
    "precio": 70,
    "imagen":"" 
}
{
    "id_producto": 1704,
    "nombre": "Alimento Dog Chow para Perro Cachorro Pequeño - 3 Kg",
    "categoria": "Alimentos",
    "marca": "Dog Chow",
    "precio": 30,
    "imagen":""
}
{
    "id_producto": 1703,
    "nombre": "Alimento Dog Chow para Perro Edad Madura - 3kg",
    "categoria": "Alimentos",
    "marca": "Dog Chow",
    "precio": 30,
    "imagen":"" 
}
{
    "id_producto": 1702,
    "nombre": "Snack Dog Chow Salud Oral Raza Pequeña - 45g",
    "categoria": "Alimentos",
    "marca": "Dog Chow",
    "precio": 5,
    "imagen":""
}
{
    "id_producto": 1701,
    "nombre": "Snack Dog Chow Salud Oral Raza Mediana y Grande - 80g",
    "categoria": "Alimentos",
    "marca": "Dog Chow",
    "precio": 5,
    "imagen":""
}
{
    "id_producto": 1605,
    "nombre": "Cat Chow Adulto Carne - 3 Kg",
    "categoria": "Alimentos",
    "marca": "Cat Chow",
    "precio": 40,
    "imagen":"" 
}
{
    "id_producto": 1604,
    "nombre": "Cat Chow Delimix Carne Pollo Salmon - 3 kg",
    "categoria": "Alimentos",
    "marca": "Cat Chow",
    "precio": 42,
    "imagen":""
}
{
    "id_producto": 1603,
    "nombre": "Cat Chow Gatitos - 1 Kg",
    "categoria": "Alimentos",
    "marca": "Cat Chow",
    "precio": 16,
    "imagen":""
}
{
    "id_producto": 1602,
    "nombre": "Cat Chow Adulto Carne - 3 Kg",
    "categoria": "Alimentos",
    "marca": "Cat Chow",
    "precio": 40,
    "imagen":""
}
{
    "id_producto": 1601,
    "nombre": "Cat Chow Adulto Pescado - 3 Kg",
    "categoria": "Alimentos",
    "marca": "Cat Chow",
    "precio": 40,
    "imagen":""
}
{
    "id_producto": 1505,
    "nombre": "Collar LED Animal Pet Azul - Large",
    "categoria": "Accesorios",
    "marca": "Animal Pet",
    "precio": 110,
    "imagen":""
}
{
    "id_producto": 1504,
    "nombre": "Cepillo Animal Pet Autolimpiante Para Perros - L",
    "categoria": "Limpieza",
    "marca": "Animal Pet",
    "precio": 185,
    "imagen":"" 
}
{
    "id_producto": 1503,
    "nombre": "Comedero Bebedero Animal Pet Curvo Naranja - Medium",
    "categoria": "Accesorios",
    "marca": "Animal Pet",
    "precio": 100,
    "imagen":"" 
}
{
    "id_producto": 1502,
    "nombre": "Collar Reflectivo Animal Pet Negro Costura Blanca - L",
    "categoria": "Accesorios",
    "marca": "Animal Pet",
    "precio": 50,
    "imagen":""
}
{
    "id_producto": 1501,
    "nombre": "Cucha Animal Pet Plastica - 87x72x75,5 Cm",
    "categoria": "Accesorios",
    "marca": "Animal Pet",
    "precio": 1180,
    "imagen":"" 
}
{
    "id_producto": 1401,
    "nombre": "Huesos De Cuero Expanded Cancat - Nº6",
    "categoria": "Alimentos",
    "marca": "CanCat",
    "precio": 24.00,
    "imagen":"" 
}
{
    "id_producto": 1206,
    "nombre": "Pedigree Biscrok Multi - 100 Gr",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 10,
    "imagen":""
}
{
    "id_producto": 1205,
    "nombre": "Lata Pedigree Carne para Perros Cachorros - 340Gr",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 15,
    "imagen":""
}
{
    "id_producto": 1204,
    "nombre": "Lata Pedigree Pollo para Perro Adulto - 340Gr",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 15,
    "imagen":""
}
{
    "id_producto": 1203,
    "nombre": "Alimento Pedigree Perro Raza Pequeña - 8kg",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 80,
    "imagen":"" 
}
{
    "id_producto": 1202,
    "nombre": "Alimento Pedigree Carne y Vegetales para Perro - 21 Kg",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 145,
    "imagen":"" 
}
{
    "id_producto": 1201,
    "nombre": "Alimento Pedigree Perro Adulto Carne Cerdo y Pollo - 21+3kg",
    "categoria": "Alimentos",
    "marca": "Pedigree",
    "precio": 160,
    "imagen":""
}
