@api = http://localhost:5000


# creando un usuario
POST {{api}}/user/signup
Content-Type: application/json

{
    "dni": 75148418,
    "apellidos": "Sanchez",
    "cantidadMascotas": 2,
    "celular": 987654321,
    "direccion": "Av. Tupac Amaru 123",
    "distrito": "Rimac",
    "email": "sanchez2@gmail.com",
    "password": "1234567",
    "nombres": "Cristhian"
}

# creando un usuario
POST {{api}}/user/signup
Content-Type: application/json

{
    "dni": 7512225,
    "apellidos": "Garcia",
    "cantidadMascotas": 2,
    "celular": 981234568,
    "direccion": "Av. Las Jefas 234",
    "distrito": "Comas",
    "email": "jefa@gmail.com",
    "password": "8754125545",
    "nombres": "Julissa"
}


//LOGIN
POST {{api}}/user/signin
Content-Type: application/json

{
    "email": "jefa@gmail.com",
    "password": "8754125545"
}


// create service
POST {{api}}/service/createService
Content-Type: application/json

{
    "id_servicio": 123,
    "categoria": "estetica",
    "especificacion": "limpieza de oidos"
}


// getService
GET {{api}}/service/getService?id_servicio=123


//CreateProduct
POST {{api}}/product/createProduct
Content-Type: application/json

{
    "id_producto": 3102,
    "nombre": "Paños Sanitarios Dogit 50 Unidades - 55,8x55,8 Cm",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 104,
    "imagen": "3102.png"
}


// create Product
POST {{api}}/product/createProduct
Content-Type: application/json

{
    "id_producto": 3103,
    "nombre": "Paños Sanitarios Dogit 30 Unidades - 55,8x55,8 Cm",
    "categoria": "Limpieza",
    "marca": "Dogit",
    "precio": 84,
    "imagen": "3103.png"
}


// get Product
GET {{api}}/product/getProduct?id_producto=102


// Create historyshop
POST {{api}}/historyshop/createHistoryshop
Content-Type: application/json

{
    "id_historial": 113,
    "cantidadCompra": 1,
    "fecha": "2019-10-21",
    "delivery": false,
    "direccion": "Calle 13",
    "distrito": "",
    "valoracion": 0,
    "dni": 7512233,
    "id_producto": 3102
}

// Get Historyshop
GET {{api}}/historyshop/getHistoryshop?id_historial=112

// Add Valoration
POST {{api}}/historyshop/addValoration
Content-Type: application/json

{
    "id_historial": 111,
    "valoracion": 5
}


//Create History cite

POST {{api}}/historycite/createHistorycite
Content-Type: application/json

{
    "id_historial": 2114,
    "dni"   : 7512233,
    "fecha" : "2019-10-21",
    "id_servicio" : 121,
    "id_mascota" : 678,
    "valoracion": 0
}


GET {{api}}/historycite/getHistorycite?id_historial=211

// Add Valoration
POST {{api}}/historycite/addValoration
Content-Type: application/json

{
    "id_historial": 211,
    "valoracion": 3
}

// register pet
POST {{api}}/pet/registerpet
Content-Type: application/json

{
    "id_mascota": 1343,
    "dni": 7512233,
    "edad": 20,
    "nombre": "cj7",
    "pelaje": "corto",
    "raza": "chihuahua",
    "sexo": "macho",
    "tamano": "pequeño",
    "tipo": "Perro"
}


// get pet
GET {{api}}/pet/getPet?id_mascota=1345


POST {{api}}/product/createProduct
Content-Type: application/json

{
    "id_producto": 3304,
    "nombre": "Shampoo Repelente Natural Protección Y Cuidado - 300 Ml",
    "categoria": "Limpieza",
    "marca": "Maskota",
    "precio": 23.60,
    "imagen":"" 
}