@api = http://localhost:5000


# creando un usuario
POST {{api}}/user/signup
Content-Type: application/json

{
    "dni": 75148418,
    "apellidos": "Sanchez",
    "cantidadMascotas": 2,
    "celular": 987654321,
    "direccion": "Av. Tupac Amaru 123",
    "distrito": "Rimac",
    "email": "sanchez2@gmail.com",
    "password": "1234567",
    "nombres": "Cristhian"
}

# creando un usuario
POST {{api}}/user/signup
Content-Type: application/json

{
    "dni": 7512225,
    "apellidos": "Garcia",
    "cantidadMascotas": 2,
    "celular": 981234568,
    "direccion": "Av. Las Jefas 234",
    "distrito": "Comas",
    "email": "jefa@gmail.com",
    "password": "8754125545",
    "nombres": "Julissa"
}


//LOGIN
POST {{api}}/user/signin
Content-Type: application/json

{
    "email": "jefa@gmail.com",
    "password":"8754125545"
}


// create service
POST {{api}}/service/createService
Content-Type: application/json

{
    "id_servicio": 123,
    "categoria": "estetica",
    "especificacion": "limpieza de oidos"
}


// getService
GET {{api}}/service/getService?id_servicio=123